import "~/styles/globals.css";
import { type Metadata } from "next";

import NavBar from "~/components/NavBar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      <SessionProvider>
        <NavBar />
        {children}
      </SessionProvider>
    </div>
  );
}
