CREATE TABLE "todolist_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "todolist_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "todolist_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "todolist_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"passwordHash" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "todolist_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "todolist_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "todolist_post" ADD CONSTRAINT "todolist_post_createdById_todolist_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."todolist_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "todolist_session" ADD CONSTRAINT "todolist_session_userId_todolist_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."todolist_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "todolist_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "todolist_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "todolist_session" USING btree ("userId");